### PR TITLE
Miscellaneous project improvements

### LINKED ISSUE #69: Quick fix permission prompt for Marshmallow
I made an oopsie when adding the storage permissions [here](https://github.com/valerio-bozzolan/AcrylicPaint/blob/master/app/src/main/java/anupam/acrylic/EasyPaint.java#L387). The `<=` should just be `<`, so that the prompt for storage access also appears on Marshmallow devices. Thanks!

Also, you should tag 2.4.0 for F-Droid after this to make sure that the correct commit gets built. (You should start tagging releases anyway, it helps F-Droid out a bunch).

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Updated Android Studio 4.0.1 -> 4.1.0

### 2nd commit
- Fix permission check for Marshmallow (closes #69)

### 3rd commit
- Rename COPYING to LICENSE

### 4th commit
- Slight miscellaneous code cleanup

### 5th commit
- Clean up duplicate code in size and erase cases

### 6th commit
- Migrate to view binding (see [here](https://developer.android.com/topic/libraries/view-binding))

### 7th commit
- Disable share feature for now, proper implementation for compileSdk above 23 requires support libraries that will severely bloat the APK (the error is FileUriExposedException)

### 8th commit
- Added a changelog for F-Droid

If/when this is merged, please [create a tag](https://github.com/valerio-bozzolan/AcrylicPaint/tags) by the name of `v2.4.0` (do not change the version code or number). It will make it so that F-Droid detects the new release and builds it, which is integral for people to get updates. Thank you! :)

### CODE REVIEW

**Comment by TacoTheDank** [comment]
@valerio-bozzolan Thanks!

The master branch doesn't seem to have the commits on it, even though it's merged. Could you fix that?

Also, could you please create a tag by the name of v2.4.0 on the master branch (after fixing the above)? It will make it so that F-Droid detects the new release and builds it, which is integral for people to get updates. Thank you! :)

**Comment by TacoTheDank** [comment]
@valerio-bozzolan Pinging again. Did you get the above message?

**Comment by valerio-bozzolan** [comment]
Ops. I forgot I've to do not use the GitHub's merge button or I obtain a rollback. Instead I have to push into my Phabricator. That will trigger my continuous integration infrastructure and will mirror the repository here in GitHub.

Every test passed anyway:

image

Should I increase versionCode from 18 to 19 this time?

Thanks

**Comment by TacoTheDank** [comment]
@valerio-bozzolan 

>Should I also increase versionCode from 18 to 19 this time like this changeset?

You would have to for F-Droid to pick up the new version anyway, so please do 😉 thanks for fixing!

**Comment by valerio-bozzolan** [comment]
That was my doubt. Thanks man.

Landed 2.4.1

https://gitpull.it/R45:e9d6e4a3becfc806c315a005ea37990b73ebbb23

https://github.com/valerio-bozzolan/AcrylicPaint/commit/e9d6e4a3becfc806c315a005ea37990b73ebbb23

**Comment by TacoTheDank** [comment]
Yay! Now to wait for F-Droid to pick it up...

**Pull request merged**
